- Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

- Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

- Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [4]:
import numpy as np
arr = np.array([1, 3, 5, 7, 9])
arr[1]

3

In [6]:
# Get third and fourth elements from the following array and add them. 5+7=12
arr = np.array([1, 3, 5, 7, 9])
arr[2] + arr[3]

12

In [7]:
arr = np.array([[2, 4, 6], [1, 3, 5]])
print('O segundo elemento da primeira linha é ', arr[0, 1]) 

O segundo elemento da primeira linha é  4


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('O quinto elemento na segunda linha ', arr[1, 4])

O quinto elemento na segunda linha  10


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


- Example Explained

arr[0, 1, 2] prints the value 6. 

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

- Negative Indexing
Use negative indexing to access an array from the end.

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('O último elemento da segunda dimensão: ', arr[1, -1])

O último elemento da segunda dimensão:  10


- Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# The result includes the start index, but excludes the end index.
arr[1:5]

array([2, 3, 4, 5])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [15]:
# Negative Slicing - Use the minus operator to refer to an index from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-3:-1]

array([5, 6])

In [16]:
# STEP - Use the step value to determine the step of the slicing:
# Return every other element from index 1 to index 5:
arr[1:5:2]

array([2, 4])

In [20]:
# Return every other element from the entire array:
arr[::2]

array([1, 3, 5, 7])

- Slicing 2-D Arrays ---

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# From the second element, slice elements from index 1 to index 4 (not included):
# Remember that second element(dimension) has index 1.

arr[1, 1:4]

array([7, 8, 9])

In [23]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 2]   # 0:2  dimensão de 0 a 1

array([3, 8])

In [25]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])