In [ ]:
NumPy: the absolute basics for beginners 
NumPy quickstart


- What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

- Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [ ]:
## NumPy Creating Arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
ara = np.zeros([3, 3], dtype=float)
print(arr)
print(type(arr))
print(ara)

- 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

- 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

- 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [1]:
import numpy as np

In [2]:
arr0D = np.array(42)

In [3]:
print(arr0D)

42


In [4]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)

[1 2 3 4 5]


In [7]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)
arr2D_1 = np.array([arr1D, arr1D])
print(arr2D_1)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [18]:
arr3D = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3],[4, 5, 6]]])
print(arr3D)
print("----------------")

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
----------------


In [19]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr2D_1.ndim)
print(arr3D.ndim)

0
1
2
2
3


In [30]:
arr5D = np.array([1, 2, 3], ndmin=5)
print(arr5D)
print("Numero de dimensões: ", arr5D.ndim)

[[[[[1 2 3]]]]]
Numero de dimensões:  5


* 1 - 1D array creation functions

The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop.
* numpy.arange creates arrays with regularly incrementing values. 
Check the documentation for complete information and examples. 

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2, 15, dtype=float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [33]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [34]:
np.linspace(1., 4., 6)   # entre 1.0 e 4.0, 6 números igualmente espaçados

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

* 2 - 2D array creation functions
The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.

In [38]:
'''
np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 
and the rest are 0, as such:
'''
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [41]:
'''
numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
returns a 1D array that is only the diagonal elements. 
The two array creation functions can be helpful while doing linear algebra, as such:
'''
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
np.diag([1, 2, 3], 1)   # numpy.diag(v, k=0)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [44]:
a = np.array([[1, 2],[3, 4]])
np.diag(a)   # dá a diagonal de "a"

array([1, 4])

* vander(x, n) 
defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1. This array creation routine is helpful in generating linear least squares models, as such:

In [45]:
np.vander(np.linspace(0, 2, 5), 2)  # (x, n-1)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [47]:
np.vander([1, 2, 3, 4], 2)  #(x, n-1)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [48]:
np.vander([1, 2, 3, 4], 4) #(x, n-1)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

# 3 - general ndarray creation functions


In [51]:
# numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64
#numpy.zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
# numpy.ones will create an array filled with 1 values. It is identical to zeros in all other respects as such:
#numpy.ones(shape, dtype=None, order='C', *, like=None)
np.ones((2, 3), dtype=object) # object é string

array([[1, 1, 1],
       [1, 1, 1]], dtype=object)

In [62]:
# The random method of the result of default_rng will create an array filled with random values between 0 and 1
from numpy.random import default_rng
default_rng().random((2, 3))

array([[0.95445675, 0.84354188, 0.30481432],
       [0.89006721, 0.30445305, 0.83974102]])

In [66]:
'''
numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), 
one per dimension with each representing variation in that dimension:
'''
b = np.indices((3, 3))
print(b)
b.ndim

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


3

# Replicating, joining, or mutating existing arrays

Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

Pra mais informações. https://numpy.org/doc/stable/user/quickstart.html#quickstart-copies-and-views

In [74]:
a = np.array([1, 2, 3, 4, 5])
b = a[:2].copy()
b += 1
print("a = ", a, "b = ", b)
print(b is a)
print(id(a))
print(id(b))

a =  [1 2 3 4 5] b =  [2 3]
False
1397991467216
1397991387952
